### ISSUE TITLE
python3 objects/cluster.py Failed

### ISSUE THREAD

**Issue by kerven88** [dguyhasnoname/k8s-cluster-checker#1]
Environmental Information：
1、K8S_VERSION：v1.18.3
2、DOCKER_VERSION：19.3.12
3、Python3 version：Python 3.7.2
4、OS system： CentOS Linux release 7.6.1810 (Core)

Whether I use docker or Python3，I get the following error：
#################################
Cluster name: kubernetes

▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁

[INFO] Fetching nodes data...

Node details:
                
  TOTAL_NODES  K8S_VERSION  TOTAL_CPU  TOTAL_MEM_GB  OS_NAME                DOCKER_VERSION  VOLUMES_IN_USE  
    
  masters: 3   v1.18.3      22         24.6GB        CentOS Linux 7 (Core)  19.3.12         0               
  worker:  0                                                                                                
  etcd:    0                                                                                                
  others:  2                                                                                                
  ----------                                                                                                
  total:   5                                                                                                

[INFO] Checking for latest and installed versions...
Traceback (most recent call last):
  File "objects/cluster.py", line 158, in <module>
    main()
  File "objects/cluster.py", line 153, in main
    call_all(options[1], options[3])
  File "objects/cluster.py", line 136, in call_all
    Cluster.get_node_data(v, l)
  File "objects/cluster.py", line 35, in get_node_data
    node._Nodes.get_nodes_details(v, l)
  File "/root/k8s-cluster-checker/objects/nodes.py", line 100, in get_nodes_details
    docker_version, item.status.node_info.kubelet_version, l)
  File "/root/k8s-cluster-checker/objects/modules/process.py", line 854, in node_version_check
    Nodes.get_latest_os_version(current_os_version)
  File "/root/k8s-cluster-checker/objects/modules/process.py", line 836, in get_latest_os_version
    return version_check.append(['OS', latest_os_version, current_os_version, status])
UnboundLocalError: local variable 'status' referenced before assignment
#################################

Can you help to see what the cause is?
TKS very much！

**Comment by dguyhasnoname** [comment]
@kerven88 Will have a look  and get back to you.

**Comment by dguyhasnoname** [comment]
@kerven88  issue has been fixed: https://github.com/dguyhasnoname/k8s-cluster-checker/commit/ba95e1d633ec67256e7f7b74e2627460fce6b8ea
